import type { Metadata } from "next"

import { MarketingPageLayout, PageSection } from "@/components/marketing/page-layout"

const privacyDescription =
  "SilentLeak privacy policy: what information is collected, how it is used, how cookies are used, and how data is protected."
const ogImage = "/brand/silentleak/silentleak-og-1200x630.png"

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: privacyDescription,
  openGraph: {
    title: "Privacy Policy | SilentLeak",
    description: privacyDescription,
    url: "/privacy",
    type: "website",
    siteName: "SilentLeak",
    images: [ogImage],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy | SilentLeak",
    description: privacyDescription,
    images: [ogImage],
  },
  alternates: {
    canonical: "/privacy",
  },
}

export default function PrivacyPage() {
  return (
    <MarketingPageLayout
      eyebrow="Legal"
      title="Privacy Policy"
      description="This policy describes what information SilentLeak collects, how it is used, how cookies are applied, and how information is protected."
    >
      <PageSection title="Overview">
        <p>
          SilentLeak is built for high-trust revenue operations. We collect
          and process information needed to operate leak monitoring across
          websites, signup paths, pricing handoffs, checkout paths, and billing recovery workflows, along
          with account management and customer support.
        </p>
      </PageSection>

      <PageSection title="Information we collect">
        <p>
          We collect information you provide directly, information generated by
          product usage, and information received through connected
          integrations.
        </p>
      </PageSection>

      <PageSection title="Account and authentication information">
        <p>Account information may include:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Name, email address, and organization details.</li>
          <li>Authentication identifiers and session metadata.</li>
          <li>Workspace roles, permissions, and account preferences.</li>
        </ul>
      </PageSection>

      <PageSection title="Billing and subscription information">
        <p>
          We process plan selection, subscription status, billing cycle dates,
          and payment status through our billing providers.
        </p>
        <p>
          SilentLeak does not store full payment card numbers. Card handling
          is performed by payment processors operating under their own
          compliance frameworks.
        </p>
      </PageSection>

      <PageSection title="Integration-related information">
        <p>
          When you connect revenue sources and external platforms, SilentLeak
          may process operational signals needed to detect leakage patterns and
          prioritize action.
        </p>
        <p>Examples may include:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Activation and onboarding progression events.</li>
          <li>Checkout, payment, invoice, or subscription lifecycle events.</li>
          <li>Store or account identifiers and configuration metadata.</li>
          <li>Source connection status and monitoring state metadata.</li>
        </ul>
      </PageSection>

      <PageSection title="Product findings and evidence">
        <p>
          SilentLeak generates detection outputs from connected source
          signals, including issue summaries, severity labels, status, and
          recommended operator actions.
        </p>
        <p>
          Findings can include supporting evidence such as event counts,
          failure-pattern indicators, and impact estimates used for
          prioritization.
        </p>
      </PageSection>

      <PageSection title="Usage and technical information">
        <p>
          We collect technical data such as IP address, device and browser
          attributes, app interaction events, and reliability telemetry used for
          platform security and service improvement.
        </p>
      </PageSection>

      <PageSection title="How we use information">
        <p>
          We use information to operate the service, generate issue detection
          insights, rank findings by estimated impact, deliver reporting
          summaries, maintain account security, provide support, and improve
          reliability and product quality.
        </p>
      </PageSection>

      <PageSection title="Cookies and similar technologies">
        <p>
          We use cookies and similar storage mechanisms needed for
          authentication, onboarding state, source connection state, and service
          security.
        </p>
        <p>Examples include:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Authentication and session cookies used by our auth provider.</li>
          <li>
            State cookies used for onboarding, demo-mode transitions, and
            connected source status.
          </li>
          <li>
            Security and anti-abuse cookies such as short sign-in cooldown
            controls.
          </li>
          <li>
            Access-review cookies that preserve submitted email identity in the
            request-access flow.
          </li>
        </ul>
        <p>
          SilentLeak does not currently use third-party advertising cookies.
          Cookie details are documented in our{" "}
          <a
            href="/cookies"
            className="vault-link"
          >
            Cookie Policy
          </a>
          .
        </p>
      </PageSection>

      <PageSection title="Sharing with service providers">
        <p>
          We share data with trusted service providers only where needed to
          operate SilentLeak. This may include hosting, database, billing,
          email delivery, analytics, and infrastructure security providers.
        </p>
        <p>
          Providers are expected to process data only for authorized purposes
          and under appropriate confidentiality and security controls.
        </p>
      </PageSection>

      <PageSection title="Data retention">
        <p>
          We retain customer data while your account is active and for a
          limited period after cancellation as needed for compliance, support,
          and legitimate business records.
        </p>
        <p>
          Some cookie-based state is temporary and expires automatically based
          on flow type, including short-lived sign-in rate-limit cookies and
          onboarding state cookies.
        </p>
      </PageSection>

      <PageSection title="Security">
        <p>
          We apply technical and organizational safeguards designed to protect
          customer information from unauthorized access, disclosure, or loss.
        </p>
      </PageSection>

      <PageSection title="Your rights and choices">
        <p>
          Depending on your jurisdiction, you may have rights to access,
          correct, export, or request deletion of personal information. You may
          also have rights to object to or restrict certain processing.
        </p>
        <p>
          To submit a request, contact us at the email below. We may need to
          verify your identity before fulfilling a request.
        </p>
      </PageSection>

      <PageSection title="Policy updates and contact">
        <p>
          We may update this policy as the product and legal requirements
          evolve. Material changes are communicated through the app or account
          email.
        </p>
        <p>
          Privacy questions can be sent to{" "}
          <a
            href="mailto:hello@silentleak.com"
            className="vault-link"
          >
            hello@silentleak.com
          </a>
          . For general support, contact{" "}
          <a
            href="mailto:hello@silentleak.com"
            className="vault-link"
          >
            hello@silentleak.com
          </a>
          .
        </p>
      </PageSection>
    </MarketingPageLayout>
  )
}
