import { MarketingPageLayout, PageSection } from "@/components/marketing/page-layout"

export default function PrivacyPage() {
  return (
    <MarketingPageLayout
      eyebrow="Legal"
      title="Privacy Policy"
      description="This policy describes what information CheckoutLeak collects, how it is used, and how it is protected."
    >
      <PageSection title="Overview">
        <p>
          CheckoutLeak is built for high-trust revenue operations. We collect
          and process information needed to operate leak detection, account
          management, and customer support.
        </p>
      </PageSection>

      <PageSection title="Information we collect">
        <p>
          We collect information you provide directly, information generated by
          product usage, and information received through connected
          integrations.
        </p>
      </PageSection>

      <PageSection title="Account and authentication information">
        <p>Account information may include:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Name, email address, and organization details.</li>
          <li>Authentication identifiers and session metadata.</li>
          <li>Workspace roles, permissions, and account preferences.</li>
        </ul>
      </PageSection>

      <PageSection title="Billing and subscription information">
        <p>
          We process plan selection, subscription status, billing cycle dates,
          and payment status through our billing providers.
        </p>
        <p>
          CheckoutLeak does not store full payment card numbers. Card handling
          is performed by payment processors operating under their own
          compliance frameworks.
        </p>
      </PageSection>

      <PageSection title="Integration-related information">
        <p>
          When you connect services such as Shopify or Stripe, CheckoutLeak may
          process operational commerce and billing signals needed to detect
          leakage patterns.
        </p>
        <p>Examples may include:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>Checkout, payment, invoice, or subscription lifecycle events.</li>
          <li>Store or account identifiers and configuration metadata.</li>
          <li>Issue and scan outputs generated by the platform.</li>
        </ul>
      </PageSection>

      <PageSection title="Usage and technical information">
        <p>
          We collect technical data such as IP address, device and browser
          attributes, app interaction events, and reliability telemetry used for
          platform security and service improvement.
        </p>
      </PageSection>

      <PageSection title="How we use information">
        <p>
          We use information to operate the service, generate issue detection
          insights, deliver reporting summaries, maintain account security,
          provide support, and improve reliability and product quality.
        </p>
      </PageSection>

      <PageSection title="Sharing with service providers">
        <p>
          We share data with trusted service providers only where needed to
          operate CheckoutLeak. This may include hosting, database, billing,
          email delivery, analytics, and infrastructure security providers.
        </p>
        <p>
          Providers are expected to process data only for authorized purposes
          and under appropriate confidentiality and security controls.
        </p>
      </PageSection>

      <PageSection title="Data retention">
        <p>
          We retain customer data while your account is active and for a
          limited period after cancellation as needed for compliance, support,
          and legitimate business records.
        </p>
      </PageSection>

      <PageSection title="Security">
        <p>
          We apply technical and organizational safeguards designed to protect
          customer information from unauthorized access, disclosure, or loss.
        </p>
      </PageSection>

      <PageSection title="Your rights and choices">
        <p>
          Depending on your jurisdiction, you may have rights to access,
          correct, export, or request deletion of personal information. You may
          also have rights to object to or restrict certain processing.
        </p>
        <p>
          To submit a request, contact us at the email below. We may need to
          verify your identity before fulfilling a request.
        </p>
      </PageSection>

      <PageSection title="Policy updates and contact">
        <p>
          We may update this policy as the product and legal requirements
          evolve. Material changes are communicated through the app or account
          email.
        </p>
        <p>
          Privacy questions can be sent to{" "}
          <a
            href="mailto:privacy@checkoutleak.com"
            className="text-primary transition-opacity hover:opacity-80"
          >
            privacy@checkoutleak.com
          </a>
          . For general support, contact{" "}
          <a
            href="mailto:support@checkoutleak.com"
            className="text-primary transition-opacity hover:opacity-80"
          >
            support@checkoutleak.com
          </a>
          .
        </p>
      </PageSection>
    </MarketingPageLayout>
  )
}
