import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { SilentLeakLogo } from "@/components/brand/logo"
import { formatCompactCurrency, formatRelativeTimestamp } from "@/lib/format"
import { getPublicReportData } from "@/server/services/report-service"

export const dynamic = "force-dynamic"

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>
}): Promise<Metadata> {
  const { token } = await params
  const report = await getPublicReportData(token)
  if (!report) return { title: "Report not found" }
  return {
    title: `${report.store.name} — SilentLeak Report`,
    description: `Surface analysis report for ${report.store.domain ?? report.store.name}. Generated by SilentLeak.`,
    robots: { index: false, follow: false },
  }
}

function ScoreBadge({
  label,
  value,
  good,
}: {
  label: string
  value: string
  good: boolean
}) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-border/60 bg-background/30 px-3.5 py-3">
      <p className="text-sm text-muted-foreground">{label}</p>
      <span
        className={`font-mono text-xs font-medium ${good ? "text-emerald-400" : "text-amber-300"}`}
      >
        {value}
      </span>
    </div>
  )
}

function SeverityDot({ severity }: { severity: string }) {
  const colors: Record<string, string> = {
    critical: "bg-red-500",
    high: "bg-orange-400",
    medium: "bg-amber-300",
    low: "bg-sky-400",
  }
  return (
    <span
      className={`inline-block h-2 w-2 shrink-0 rounded-full ${colors[severity] ?? "bg-border"}`}
    />
  )
}

function GeoBar({ score }: { score: number }) {
  const filled = Math.min(5, Math.max(0, score))
  return (
    <div className="flex gap-1">
      {[1, 2, 3, 4, 5].map((i) => (
        <div
          key={i}
          className={`h-1.5 flex-1 rounded-full ${i <= filled ? "bg-emerald-400" : "bg-border/50"}`}
        />
      ))}
    </div>
  )
}

function BusinessTypeLabel(type: string | null) {
  const labels: Record<string, string> = {
    agency: "Agency",
    saas: "SaaS",
    ecommerce: "Ecommerce",
    service_business: "Service business",
    mixed: "Mixed revenue model",
    unknown: "Source type pending",
  }
  return labels[type ?? "unknown"] ?? "Source type pending"
}

function RevenuePathLabel(clarity: string | null) {
  if (clarity === "clear") return "Revenue path visible"
  if (clarity === "partial") return "Revenue path incomplete"
  if (clarity === "none") return "No clear revenue path"
  return "Revenue path pending"
}

function CwvRating({ rating }: { rating: string | null }) {
  if (!rating) return <span className="text-muted-foreground">Not measured</span>
  const colors: Record<string, string> = {
    good: "text-emerald-400",
    needs_improvement: "text-amber-300",
    poor: "text-red-400",
  }
  const labels: Record<string, string> = {
    good: "Good",
    needs_improvement: "Needs improvement",
    poor: "Poor",
  }
  return (
    <span className={`font-medium ${colors[rating] ?? "text-muted-foreground"}`}>
      {labels[rating] ?? rating}
    </span>
  )
}

export default async function PublicReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const report = await getPublicReportData(token)

  if (!report) notFound()

  const a = report.analysis
  const hardIssues = report.issues.filter((i) => i.severity !== "low")
  const opportunities = report.issues.filter((i) => i.severity === "low")

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-border/60 bg-sidebar/60 backdrop-blur">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4 sm:px-6">
          <SilentLeakLogo />
          <p className="font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground/60 uppercase">
            Surface Report
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6">

        {/* Source identity */}
        <section className="space-y-1">
          <p className="data-mono text-muted-foreground">Surface analysis</p>
          <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">
            {report.store.domain ?? report.store.name}
          </h1>
          <p className="text-sm text-muted-foreground">
            {report.label ?? "SilentLeak scan report"}
            {report.scan?.completedAt
              ? ` · Analyzed ${formatRelativeTimestamp(report.scan.completedAt)}`
              : ""}
          </p>
        </section>

        {/* Top metrics */}
        <section className="grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl border border-border/60 bg-card/60 p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-[0.07em] font-mono">Business model</p>
            <p className="mt-2 text-lg font-semibold">{BusinessTypeLabel(a?.businessType ?? null)}</p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              {a?.revenueModel?.replace(/_/g, " ") ?? "Revenue model pending"}
            </p>
          </div>
          <div className="rounded-xl border border-border/60 bg-card/60 p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-[0.07em] font-mono">Revenue path</p>
            <p className="mt-2 text-lg font-semibold">{RevenuePathLabel(a?.revenuePathClarity ?? null)}</p>
            {a?.primaryCtaLabel ? (
              <p className="mt-0.5 text-xs text-muted-foreground">
                Primary action: {a.primaryCtaLabel}
              </p>
            ) : null}
          </div>
          <div className="rounded-xl border border-border/60 bg-card/60 p-4">
            <p className="text-xs text-muted-foreground uppercase tracking-[0.07em] font-mono">Open issues</p>
            <p className="mt-2 text-lg font-semibold">{hardIssues.length}</p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              {opportunities.length > 0
                ? `${opportunities.length} optimization${opportunities.length !== 1 ? "s" : ""} also available`
                : hardIssues.length === 0
                  ? "No critical issues detected"
                  : "Ranked by exposure"}
            </p>
          </div>
        </section>

        <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
          <div className="space-y-6">

            {/* Issues */}
            {hardIssues.length > 0 ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">Active issues</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    {hardIssues.length} findings · sorted by exposure
                  </p>
                </div>
                <ul className="divide-y divide-border/50">
                  {hardIssues.map((issue) => (
                    <li key={issue.id} className="flex items-start gap-3 px-5 py-4">
                      <SeverityDot severity={issue.severity} />
                      <div className="min-w-0 flex-1">
                        <p className="text-sm font-medium leading-snug">{issue.title}</p>
                        <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                          {issue.summary}
                        </p>
                      </div>
                      {issue.estimatedMonthlyRevenueImpact > 0 ? (
                        <p className="shrink-0 font-mono text-xs text-amber-300">
                          {formatCompactCurrency(issue.estimatedMonthlyRevenueImpact)}
                        </p>
                      ) : null}
                    </li>
                  ))}
                </ul>
              </section>
            ) : (
              <section className="rounded-xl border border-border/60 bg-card/40 px-5 py-6">
                <p className="text-sm font-medium text-emerald-400">No critical issues detected</p>
                <p className="mt-1 text-xs text-muted-foreground">
                  Core revenue paths appear healthy based on the latest surface analysis.
                </p>
              </section>
            )}

            {/* Optimization opportunities */}
            {opportunities.length > 0 ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">Optimization opportunities</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    {opportunities.length} improvement{opportunities.length !== 1 ? "s" : ""} available
                  </p>
                </div>
                <ul className="divide-y divide-border/50">
                  {opportunities.map((issue) => (
                    <li key={issue.id} className="flex items-start gap-3 px-5 py-4">
                      <span className="mt-1 inline-block h-2 w-2 shrink-0 rounded-full bg-sky-400/60" />
                      <div className="min-w-0 flex-1">
                        <p className="text-sm font-medium leading-snug">{issue.title}</p>
                        <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                          {issue.summary}
                        </p>
                      </div>
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}

            {/* SEO */}
            {a ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">SEO signals</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    Static HTML — what search crawlers see
                  </p>
                </div>
                <div className="space-y-2 p-4">
                  <ScoreBadge
                    label="Page title"
                    value={a.metaTitleQuality === "good" ? "Good" : a.metaTitleQuality === "missing" ? "Missing" : a.metaTitleQuality ?? "Pending"}
                    good={a.metaTitleQuality === "good"}
                  />
                  <ScoreBadge
                    label="Meta description"
                    value={a.metaDescriptionQuality === "good" ? "Good" : a.metaDescriptionQuality === "missing" ? "Missing" : a.metaDescriptionQuality ?? "Pending"}
                    good={a.metaDescriptionQuality === "good"}
                  />
                  <ScoreBadge
                    label="H1 headings"
                    value={a.h1Count === null ? "Pending" : a.h1Count === 1 ? "1 (correct)" : `${a.h1Count} found`}
                    good={a.h1Count === 1}
                  />
                  <ScoreBadge
                    label="Open Graph"
                    value={a.hasOpenGraph ? "Present" : "Missing"}
                    good={a.hasOpenGraph}
                  />
                  <ScoreBadge
                    label="Mobile viewport"
                    value={a.hasMobileViewport ? "Configured" : "Missing"}
                    good={a.hasMobileViewport}
                  />
                </div>
              </section>
            ) : null}
          </div>

          <div className="space-y-6">

            {/* GEO */}
            {a ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">GEO readiness</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    AI search citation potential
                  </p>
                </div>
                <div className="p-4 space-y-3">
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <p className="text-sm text-muted-foreground">Score</p>
                      <p className="font-mono text-sm font-medium">
                        {a.geoReadinessScore ?? 0}/5
                      </p>
                    </div>
                    <GeoBar score={a.geoReadinessScore ?? 0} />
                  </div>
                  <div className="space-y-1.5 pt-1">
                    <p className="font-mono text-[0.64rem] uppercase tracking-[0.07em] text-muted-foreground/60">
                      Detected schema
                    </p>
                    {a.hasStructuredData && a.structuredDataTypes.length > 0 ? (
                      <div className="flex flex-wrap gap-1.5">
                        {a.structuredDataTypes.map((t) => (
                          <span
                            key={t}
                            className="rounded border border-emerald-400/25 bg-emerald-400/[0.07] px-2 py-0.5 font-mono text-[0.62rem] text-emerald-400"
                          >
                            {t}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <p className="text-xs text-muted-foreground">No structured data detected</p>
                    )}
                    {a.hasFaqSchema ? null : (
                      <p className="text-xs text-amber-300/80">FAQPage schema missing</p>
                    )}
                  </div>
                </div>
              </section>
            ) : null}

            {/* Core Web Vitals */}
            {a && (a.lcpMs !== null || a.clsScore !== null) ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">Core Web Vitals</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    Measured in real Chromium
                  </p>
                </div>
                <div className="space-y-3 p-4 text-sm">
                  {a.lcpMs !== null ? (
                    <div className="flex items-center justify-between">
                      <p className="text-muted-foreground">LCP</p>
                      <div className="text-right">
                        <p className="font-mono text-xs">{Math.round(a.lcpMs)}ms</p>
                        <CwvRating rating={a.lcpRating} />
                      </div>
                    </div>
                  ) : null}
                  {a.clsScore !== null ? (
                    <div className="flex items-center justify-between">
                      <p className="text-muted-foreground">CLS</p>
                      <div className="text-right">
                        <p className="font-mono text-xs">{a.clsScore.toFixed(3)}</p>
                        <CwvRating rating={a.clsRating} />
                      </div>
                    </div>
                  ) : null}
                  {a.responseTimeMs !== null ? (
                    <div className="flex items-center justify-between">
                      <p className="text-muted-foreground">Response time</p>
                      <p className="font-mono text-xs">{Math.round(a.responseTimeMs)}ms</p>
                    </div>
                  ) : null}
                </div>
              </section>
            ) : null}

            {/* Mobile quality */}
            {a ? (
              <section className="rounded-xl border border-border/60 bg-card/40">
                <div className="border-b border-border/60 px-5 py-3.5">
                  <p className="text-sm font-medium">Mobile quality</p>
                  <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.06em] text-muted-foreground">
                    375px viewport
                  </p>
                </div>
                <div className="space-y-2 p-4">
                  <ScoreBadge
                    label="Layout overflow"
                    value={a.mobileViewportOverflow ? "Detected" : "Clean"}
                    good={!a.mobileViewportOverflow}
                  />
                  <ScoreBadge
                    label="H1 font size"
                    value={a.mobileH1IsOversized ? "Oversized" : "Good"}
                    good={!a.mobileH1IsOversized}
                  />
                  <ScoreBadge
                    label="Copy quality"
                    value={a.hasAiGenericCopy ? "Generic patterns detected" : "No flags"}
                    good={!a.hasAiGenericCopy}
                  />
                </div>
              </section>
            ) : null}
          </div>
        </div>

        {/* Footer */}
        <footer className="border-t border-border/60 pt-6 pb-10">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs text-muted-foreground">
                Generated by{" "}
                <a
                  href="https://www.silentleak.com"
                  className="text-foreground hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  SilentLeak
                </a>
                {" "}&middot; Revenue surface intelligence
              </p>
              <p className="mt-0.5 text-xs text-muted-foreground/60">
                Report expires {new Date(report.expiresAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
              </p>
            </div>
            <a
              href="https://www.silentleak.com"
              className="rounded-lg border border-border/60 px-3.5 py-2 text-xs text-muted-foreground transition-colors hover:text-foreground"
            >
              Monitor your own source
            </a>
          </div>
        </footer>
      </main>
    </div>
  )
}
